import { AreaChart } from 'lucide-react';

export const areaChartData = {
  id: 'area-chart',
  name: 'Area Chart',
  icon: AreaChart,
  galleryDsl:
    'vis area\ndata\n  - time 2018\n    value 201\n  - time 2019\n    value 221\n  - time 2020\n    value 307\n  - time 2021\n    value 460\n  - time 2022\n    value 620\n  - time 2023\n    value 830\n  - time 2024\n    value 1080\ntitle "EV Sales Trend"\naxisXTitle Year\naxisYTitle "Sales (10K)"',
  galleryJson: {
    type: 'area',
    data: [
      { time: 2018, value: 201 },
      { time: 2019, value: 221 },
      { time: 2020, value: 307 },
      { time: 2021, value: 460 },
      { time: 2022, value: 620 },
      { time: 2023, value: 830 },
      { time: 2024, value: 1080 },
    ],
    title: 'EV Sales Trend',
    axisXTitle: 'Year',
    axisYTitle: 'Sales (10K)',
  },
  description:
    'An area chart is a statistical chart that reflects numerical changes as an ordered variable changes, similar in principle to a line chart. The distinctive feature of an area chart is that the area between the line and the independent variable axis is filled with color.',
  knowledge: {
    introduction:
      'An area chart is a statistical chart that reflects numerical changes as an ordered variable changes, similar in principle to a line chart. The distinctive feature of an area chart is that the area between the line and the independent variable axis is filled with color.',
    useCases: [
      'To show trend changes in data under a continuous independent variable while also observing changes in total data volume',
      'For example, displacement = velocity × time: s = v × t. If the x-axis is time t and the y-axis is velocity v at each moment, using an area chart allows you not only to observe the trend of velocity over time but also to perceive the change in displacement distance based on the size of the area',
    ],
    config: [
      {
        name: 'Configuration Options',
        config: [
          {
            property: 'type',
            type: 'required',
            valueType: 'string',
            description: 'Value must be "area".',
          },
          {
            property: 'data',
            type: 'required',
            valueType: 'Object[]',
            description: 'Chart data.',
          },
          {
            property: 'data.time',
            type: 'required',
            valueType: 'string | number',
            description: 'Time series name.',
          },
          {
            property: 'data.value',
            type: 'required',
            valueType: 'number',
            description: 'Data value.',
          },
          {
            property: 'data.group',
            type: 'optional',
            valueType: 'string',
            description: 'Group name. Required when stacking is enabled.',
          },
          {
            property: 'stack',
            type: 'optional',
            valueType: 'boolean',
            description: 'Whether to enable stacking.',
          },
          {
            property: 'title',
            type: 'optional',
            valueType: 'string',
            description: 'Chart title.',
          },
          {
            property: 'axisXTitle',
            type: 'optional',
            valueType: 'string',
            description: 'X-axis title.',
          },
          {
            property: 'axisYTitle',
            type: 'optional',
            valueType: 'string',
            description: 'Y-axis title.',
          },
          {
            property: 'theme',
            type: 'optional',
            valueType: "'default' | 'dark' | 'academy'",
            description: 'Chart theme, default is "default".',
          },
          {
            property: 'style',
            type: 'optional',
            valueType: 'Object',
            description: 'Chart style.',
          },
          {
            property: 'style.backgroundColor',
            type: 'optional',
            valueType: 'string',
            description: 'Must be a valid color value.',
          },
          {
            property: 'style.palette',
            type: 'optional',
            valueType: 'string[]',
            description: 'Must be an array of valid color values.',
          },
          {
            property: 'style.lineWidth',
            type: 'optional',
            valueType: 'number',
            description: 'Stroke width, value must be greater than or equal to 0.',
          },
        ],
      },
    ],
  },
  examples: [
    {
      title: 'Global Electric Vehicle Sales Trend',
      description: 'Global Electric Vehicle Sales Trend',
      json: {
        type: 'area',
        data: [
          { time: 2018, value: 201 },
          { time: 2019, value: 221 },
          { time: 2020, value: 307 },
          { time: 2021, value: 460 },
          { time: 2022, value: 620 },
          { time: 2023, value: 830 },
          { time: 2024, value: 1080 },
        ],
        title: 'EV Sales Trend',
        axisXTitle: 'Year',
        axisYTitle: 'Sales (10K)',
      },
      dsl: 'vis area\ndata\n  - time 2018\n    value 201\n  - time 2019\n    value 221\n  - time 2020\n    value 307\n  - time 2021\n    value 460\n  - time 2022\n    value 620\n  - time 2023\n    value 830\n  - time 2024\n    value 1080\ntitle "EV Sales Trend"\naxisXTitle Year\naxisYTitle "Sales (10K)"',
    },
    {
      title: 'China Power Structure Change Trend, Custom Colors',
      description: 'China Power Structure Change Trend',
      json: {
        type: 'area',
        data: [
          { time: 2018, value: 3800, group: 'Thermal' },
          { time: 2019, value: 3750, group: 'Thermal' },
          { time: 2020, value: 3650, group: 'Thermal' },
          { time: 2021, value: 3600, group: 'Thermal' },
          { time: 2022, value: 3550, group: 'Thermal' },
          { time: 2023, value: 3480, group: 'Thermal' },
          { time: 2024, value: 3400, group: 'Thermal' },
          { time: 2018, value: 1200, group: 'Hydro' },
          { time: 2019, value: 1250, group: 'Hydro' },
          { time: 2020, value: 1300, group: 'Hydro' },
          { time: 2021, value: 1350, group: 'Hydro' },
          { time: 2022, value: 1380, group: 'Hydro' },
          { time: 2023, value: 1420, group: 'Hydro' },
          { time: 2024, value: 1450, group: 'Hydro' },
          { time: 2018, value: 500, group: 'Nuclear' },
          { time: 2019, value: 550, group: 'Nuclear' },
          { time: 2020, value: 600, group: 'Nuclear' },
          { time: 2021, value: 650, group: 'Nuclear' },
          { time: 2022, value: 700, group: 'Nuclear' },
          { time: 2023, value: 750, group: 'Nuclear' },
          { time: 2024, value: 800, group: 'Nuclear' },
        ],
        stack: true,
        title: 'China Power Structure Change Trend',
        axisXTitle: 'Year',
        axisYTitle: 'Power Generation (TWh)',
        style: { palette: ['#A855F7', '#38BDF8', '#34D399'], backgroundColor: '#f8f7ff' },
      },
      dsl: 'vis area\ndata\n  - time 2018\n    value 3800\n    group Thermal\n  - time 2019\n    value 3750\n    group Thermal\n  - time 2020\n    value 3650\n    group Thermal\n  - time 2021\n    value 3600\n    group Thermal\n  - time 2022\n    value 3550\n    group Thermal\n  - time 2023\n    value 3480\n    group Thermal\n  - time 2024\n    value 3400\n    group Thermal\n  - time 2018\n    value 1200\n    group Hydro\n  - time 2019\n    value 1250\n    group Hydro\n  - time 2020\n    value 1300\n    group Hydro\n  - time 2021\n    value 1350\n    group Hydro\n  - time 2022\n    value 1380\n    group Hydro\n  - time 2023\n    value 1420\n    group Hydro\n  - time 2024\n    value 1450\n    group Hydro\n  - time 2018\n    value 500\n    group Nuclear\n  - time 2019\n    value 550\n    group Nuclear\n  - time 2020\n    value 600\n    group Nuclear\n  - time 2021\n    value 650\n    group Nuclear\n  - time 2022\n    value 700\n    group Nuclear\n  - time 2023\n    value 750\n    group Nuclear\n  - time 2024\n    value 800\n    group Nuclear\nstack true\ntitle "China Power Structure Change Trend"\naxisXTitle Year\naxisYTitle "Power Generation (TWh)"\nstyle\n  palette\n    - "#A855F7"\n    - "#38BDF8"\n    - "#34D399"\n  backgroundColor "#f8f7ff"',
    },
    {
      title: 'Global Cloud Computing Market Size Trend, Custom Palette',
      description: 'Global Cloud Computing Market Size Trend',
      json: {
        type: 'area',
        data: [
          { time: 2019, value: 350, group: 'IaaS' },
          { time: 2020, value: 480, group: 'IaaS' },
          { time: 2021, value: 650, group: 'IaaS' },
          { time: 2022, value: 830, group: 'IaaS' },
          { time: 2023, value: 1050, group: 'IaaS' },
          { time: 2024, value: 1320, group: 'IaaS' },
          { time: 2019, value: 520, group: 'SaaS' },
          { time: 2020, value: 680, group: 'SaaS' },
          { time: 2021, value: 870, group: 'SaaS' },
          { time: 2022, value: 1100, group: 'SaaS' },
          { time: 2023, value: 1380, group: 'SaaS' },
          { time: 2024, value: 1700, group: 'SaaS' },
          { time: 2019, value: 180, group: 'PaaS' },
          { time: 2020, value: 250, group: 'PaaS' },
          { time: 2021, value: 340, group: 'PaaS' },
          { time: 2022, value: 440, group: 'PaaS' },
          { time: 2023, value: 560, group: 'PaaS' },
          { time: 2024, value: 700, group: 'PaaS' },
        ],
        title: 'Global Cloud Computing Market Size Trend',
        axisXTitle: 'Year',
        axisYTitle: 'Market Size (100M USD)',
        theme: 'academy',
        style: { palette: ['#C45B42', '#7D8C6E', '#D4A373'], backgroundColor: '#FBF8F4' },
      },
      dsl: 'vis area\ndata\n  - time 2019\n    value 350\n    group IaaS\n  - time 2020\n    value 480\n    group IaaS\n  - time 2021\n    value 650\n    group IaaS\n  - time 2022\n    value 830\n    group IaaS\n  - time 2023\n    value 1050\n    group IaaS\n  - time 2024\n    value 1320\n    group IaaS\n  - time 2019\n    value 520\n    group SaaS\n  - time 2020\n    value 680\n    group SaaS\n  - time 2021\n    value 870\n    group SaaS\n  - time 2022\n    value 1100\n    group SaaS\n  - time 2023\n    value 1380\n    group SaaS\n  - time 2024\n    value 1700\n    group SaaS\n  - time 2019\n    value 180\n    group PaaS\n  - time 2020\n    value 250\n    group PaaS\n  - time 2021\n    value 340\n    group PaaS\n  - time 2022\n    value 440\n    group PaaS\n  - time 2023\n    value 560\n    group PaaS\n  - time 2024\n    value 700\n    group PaaS\ntitle "Global Cloud Computing Market Size Trend"\naxisXTitle Year\naxisYTitle "Market Size (100M USD)"\ntheme academy\nstyle\n  palette\n    - "#C45B42"\n    - "#7D8C6E"\n    - "#D4A373"\n  backgroundColor "#FBF8F4"',
    },
  ],
};
