export const boxplotData = {
  id: 'boxplot',
  name: 'Boxplot',
  galleryDsl:
    'vis boxplot\ndata\n  - category Math\n    value 72\n  - category Math\n    value 85\n  - category Math\n    value 68\n  - category Math\n    value 91\n  - category Math\n    value 76\n  - category Math\n    value 83\n  - category Math\n    value 65\n  - category Math\n    value 88\n  - category Math\n    value 79\n  - category Math\n    value 94\n  - category Math\n    value 70\n  - category Math\n    value 82\n  - category Math\n    value 86\n  - category Math\n    value 74\n  - category Math\n    value 90\n  - category Math\n    value 67\n  - category Math\n    value 78\n  - category Math\n    value 84\n  - category Math\n    value 73\n  - category Math\n    value 89\n  - category History\n    value 78\n  - category History\n    value 82\n  - category History\n    value 75\n  - category History\n    value 88\n  - category History\n    value 80\n  - category History\n    value 85\n  - category History\n    value 72\n  - category History\n    value 90\n  - category History\n    value 77\n  - category History\n    value 83\n  - category History\n    value 79\n  - category History\n    value 86\n  - category History\n    value 74\n  - category History\n    value 91\n  - category History\n    value 76\n  - category History\n    value 84\n  - category History\n    value 81\n  - category History\n    value 73\n  - category History\n    value 87\n  - category English\n    value 65\n  - category English\n    value 78\n  - category English\n    value 82\n  - category English\n    value 70\n  - category English\n    value 86\n  - category English\n    value 74\n  - category English\n    value 80\n  - category English\n    value 68\n  - category English\n    value 84\n  - category English\n    value 72\n  - category English\n    value 88\n  - category English\n    value 76\n  - category English\n    value 81\n  - category English\n    value 67\n  - category English\n    value 85\n  - category English\n    value 73\n  - category English\n    value 79\n  - category English\n    value 83\n  - category English\n    value 71\n  - category English\n    value 77\n  - category Physics\n    value 58\n  - category Physics\n    value 72\n  - category Physics\n    value 85\n  - category Physics\n    value 63\n  - category Physics\n    value 90\n  - category Physics\n    value 68\n  - category Physics\n    value 78\n  - category Physics\n    value 55\n  - category Physics\n    value 82\n  - category Physics\n    value 70\n  - category Physics\n    value 92\n  - category Physics\n    value 65\n  - category Physics\n    value 76\n  - category Physics\n    value 60\n  - category Physics\n    value 88\n  - category Physics\n    value 74\n  - category Physics\n    value 80\n  - category Physics\n    value 67\n  - category Physics\n    value 83\n  - category Physics\n    value 62\n  - category Physics\n    value 75\ntitle "Exam Scores by Subject"\naxisXTitle Subject\naxisYTitle Score',
  galleryJson: {
    type: 'boxplot',
    data: [
      { category: 'Math', value: 72 },
      { category: 'Math', value: 85 },
      { category: 'Math', value: 68 },
      { category: 'Math', value: 91 },
      { category: 'Math', value: 76 },
      { category: 'Math', value: 83 },
      { category: 'Math', value: 65 },
      { category: 'Math', value: 88 },
      { category: 'Math', value: 79 },
      { category: 'Math', value: 94 },
      { category: 'Math', value: 70 },
      { category: 'Math', value: 82 },
      { category: 'Math', value: 86 },
      { category: 'Math', value: 74 },
      { category: 'Math', value: 90 },
      { category: 'Math', value: 67 },
      { category: 'Math', value: 78 },
      { category: 'Math', value: 84 },
      { category: 'Math', value: 73 },
      { category: 'Math', value: 89 },
      { category: 'History', value: 78 },
      { category: 'History', value: 82 },
      { category: 'History', value: 75 },
      { category: 'History', value: 88 },
      { category: 'History', value: 80 },
      { category: 'History', value: 85 },
      { category: 'History', value: 72 },
      { category: 'History', value: 90 },
      { category: 'History', value: 77 },
      { category: 'History', value: 83 },
      { category: 'History', value: 79 },
      { category: 'History', value: 86 },
      { category: 'History', value: 74 },
      { category: 'History', value: 91 },
      { category: 'History', value: 76 },
      { category: 'History', value: 84 },
      { category: 'History', value: 81 },
      { category: 'History', value: 73 },
      { category: 'History', value: 87 },
      { category: 'English', value: 65 },
      { category: 'English', value: 78 },
      { category: 'English', value: 82 },
      { category: 'English', value: 70 },
      { category: 'English', value: 86 },
      { category: 'English', value: 74 },
      { category: 'English', value: 80 },
      { category: 'English', value: 68 },
      { category: 'English', value: 84 },
      { category: 'English', value: 72 },
      { category: 'English', value: 88 },
      { category: 'English', value: 76 },
      { category: 'English', value: 81 },
      { category: 'English', value: 67 },
      { category: 'English', value: 85 },
      { category: 'English', value: 73 },
      { category: 'English', value: 79 },
      { category: 'English', value: 83 },
      { category: 'English', value: 71 },
      { category: 'English', value: 77 },
      { category: 'Physics', value: 58 },
      { category: 'Physics', value: 72 },
      { category: 'Physics', value: 85 },
      { category: 'Physics', value: 63 },
      { category: 'Physics', value: 90 },
      { category: 'Physics', value: 68 },
      { category: 'Physics', value: 78 },
      { category: 'Physics', value: 55 },
      { category: 'Physics', value: 82 },
      { category: 'Physics', value: 70 },
      { category: 'Physics', value: 92 },
      { category: 'Physics', value: 65 },
      { category: 'Physics', value: 76 },
      { category: 'Physics', value: 60 },
      { category: 'Physics', value: 88 },
      { category: 'Physics', value: 74 },
      { category: 'Physics', value: 80 },
      { category: 'Physics', value: 67 },
      { category: 'Physics', value: 83 },
      { category: 'Physics', value: 62 },
      { category: 'Physics', value: 75 },
    ],
    title: 'Exam Scores by Subject',
    axisXTitle: 'Subject',
    axisYTitle: 'Score',
  },
  description:
    'A boxplot is a statistical chart used to display data distribution, central tendency, and outliers. The box represents the interquartile range, the whiskers represent the range of data extremes, and outliers are marked individually. It is well-suited for visually comparing the distribution characteristics of different groups of data.',
  knowledge: {
    introduction:
      'A boxplot is a statistical chart used to display data distribution, central tendency, and outliers. The box represents the interquartile range, the whiskers represent the range of data extremes, and outliers are marked individually. It is well-suited for visually comparing the distribution characteristics of different groups of data.',
    useCases: [
      'Used to display the distribution of one or more groups of data, such as score distributions, experimental results, financial data, etc.',
      'Suitable for highlighting the median, range, and outliers of data',
    ],
    config: [
      {
        name: 'Configuration Options',
        config: [
          {
            property: 'type',
            type: 'required',
            valueType: 'string',
            description: 'Value must be "boxplot".',
          },
          {
            property: 'data',
            type: 'required',
            valueType: 'Object[]',
            description: 'Chart data.',
          },
          {
            property: 'data.category',
            type: 'required',
            valueType: 'string',
            description: 'Category name.',
          },
          {
            property: 'data.value',
            type: 'required',
            valueType: 'number',
            description: 'Data value.',
          },
          {
            property: 'data.group',
            type: 'optional',
            valueType: 'string',
            description: 'Group name, used for multi-group data comparison.',
          },
          {
            property: 'title',
            type: 'optional',
            valueType: 'string',
            description: 'Chart title.',
          },
          {
            property: 'axisXTitle',
            type: 'optional',
            valueType: 'string',
            description: 'X-axis title.',
          },
          {
            property: 'axisYTitle',
            type: 'optional',
            valueType: 'string',
            description: 'Y-axis title.',
          },
          {
            property: 'theme',
            type: 'optional',
            valueType: "'default' | 'dark' | 'academy'",
            description: 'Chart theme, default is "default".',
          },
          {
            property: 'style',
            type: 'optional',
            valueType: 'Object',
            description: 'Chart style.',
          },
          {
            property: 'style.backgroundColor',
            type: 'optional',
            valueType: 'string',
            description: 'Must be a valid color value.',
          },
          {
            property: 'style.palette',
            type: 'optional',
            valueType: 'string[]',
            description: 'Color palette.',
          },
          {
            property: 'style.startAtZero',
            type: 'optional',
            valueType: 'boolean',
            description: 'Whether the Y-axis starts from zero, default is false.',
          },
          {
            property: 'axisXTitle',
            type: 'optional',
            valueType: 'string',
            description: 'X-axis title.',
          },
          {
            property: 'axisYTitle',
            type: 'optional',
            valueType: 'string',
            description: 'Y-axis title.',
          },
        ],
      },
    ],
  },
  examples: [
    {
      title:
        'Four-Subject Exam Score Distribution: Score distribution comparison of 20 students each in Math, History, English, and Physics.',
      description:
        'Four-Subject Exam Score Distribution: Score distribution comparison of 20 students each in Math, History, English, and Physics.',
      json: {
        type: 'boxplot',
        data: [
          { category: 'Math', value: 72 },
          { category: 'Math', value: 85 },
          { category: 'Math', value: 68 },
          { category: 'Math', value: 91 },
          { category: 'Math', value: 76 },
          { category: 'Math', value: 83 },
          { category: 'Math', value: 65 },
          { category: 'Math', value: 88 },
          { category: 'Math', value: 79 },
          { category: 'Math', value: 94 },
          { category: 'Math', value: 70 },
          { category: 'Math', value: 82 },
          { category: 'Math', value: 86 },
          { category: 'Math', value: 74 },
          { category: 'Math', value: 90 },
          { category: 'Math', value: 67 },
          { category: 'Math', value: 78 },
          { category: 'Math', value: 84 },
          { category: 'Math', value: 73 },
          { category: 'Math', value: 89 },
          { category: 'History', value: 78 },
          { category: 'History', value: 82 },
          { category: 'History', value: 75 },
          { category: 'History', value: 88 },
          { category: 'History', value: 80 },
          { category: 'History', value: 85 },
          { category: 'History', value: 72 },
          { category: 'History', value: 90 },
          { category: 'History', value: 77 },
          { category: 'History', value: 83 },
          { category: 'History', value: 79 },
          { category: 'History', value: 86 },
          { category: 'History', value: 74 },
          { category: 'History', value: 91 },
          { category: 'History', value: 76 },
          { category: 'History', value: 84 },
          { category: 'History', value: 81 },
          { category: 'History', value: 73 },
          { category: 'History', value: 87 },
          { category: 'English', value: 65 },
          { category: 'English', value: 78 },
          { category: 'English', value: 82 },
          { category: 'English', value: 70 },
          { category: 'English', value: 86 },
          { category: 'English', value: 74 },
          { category: 'English', value: 80 },
          { category: 'English', value: 68 },
          { category: 'English', value: 84 },
          { category: 'English', value: 72 },
          { category: 'English', value: 88 },
          { category: 'English', value: 76 },
          { category: 'English', value: 81 },
          { category: 'English', value: 67 },
          { category: 'English', value: 85 },
          { category: 'English', value: 73 },
          { category: 'English', value: 79 },
          { category: 'English', value: 83 },
          { category: 'English', value: 71 },
          { category: 'English', value: 77 },
          { category: 'Physics', value: 58 },
          { category: 'Physics', value: 72 },
          { category: 'Physics', value: 85 },
          { category: 'Physics', value: 63 },
          { category: 'Physics', value: 90 },
          { category: 'Physics', value: 68 },
          { category: 'Physics', value: 78 },
          { category: 'Physics', value: 55 },
          { category: 'Physics', value: 82 },
          { category: 'Physics', value: 70 },
          { category: 'Physics', value: 92 },
          { category: 'Physics', value: 65 },
          { category: 'Physics', value: 76 },
          { category: 'Physics', value: 60 },
          { category: 'Physics', value: 88 },
          { category: 'Physics', value: 74 },
          { category: 'Physics', value: 80 },
          { category: 'Physics', value: 67 },
          { category: 'Physics', value: 83 },
          { category: 'Physics', value: 62 },
          { category: 'Physics', value: 75 },
        ],
        title: 'Exam Scores by Subject',
        axisXTitle: 'Subject',
        axisYTitle: 'Score',
      },
      dsl: 'vis boxplot\ndata\n  - category Math\n    value 72\n  - category Math\n    value 85\n  - category Math\n    value 68\n  - category Math\n    value 91\n  - category Math\n    value 76\n  - category Math\n    value 83\n  - category Math\n    value 65\n  - category Math\n    value 88\n  - category Math\n    value 79\n  - category Math\n    value 94\n  - category Math\n    value 70\n  - category Math\n    value 82\n  - category Math\n    value 86\n  - category Math\n    value 74\n  - category Math\n    value 90\n  - category Math\n    value 67\n  - category Math\n    value 78\n  - category Math\n    value 84\n  - category Math\n    value 73\n  - category Math\n    value 89\n  - category History\n    value 78\n  - category History\n    value 82\n  - category History\n    value 75\n  - category History\n    value 88\n  - category History\n    value 80\n  - category History\n    value 85\n  - category History\n    value 72\n  - category History\n    value 90\n  - category History\n    value 77\n  - category History\n    value 83\n  - category History\n    value 79\n  - category History\n    value 86\n  - category History\n    value 74\n  - category History\n    value 91\n  - category History\n    value 76\n  - category History\n    value 84\n  - category History\n    value 81\n  - category History\n    value 73\n  - category History\n    value 87\n  - category English\n    value 65\n  - category English\n    value 78\n  - category English\n    value 82\n  - category English\n    value 70\n  - category English\n    value 86\n  - category English\n    value 74\n  - category English\n    value 80\n  - category English\n    value 68\n  - category English\n    value 84\n  - category English\n    value 72\n  - category English\n    value 88\n  - category English\n    value 76\n  - category English\n    value 81\n  - category English\n    value 67\n  - category English\n    value 85\n  - category English\n    value 73\n  - category English\n    value 79\n  - category English\n    value 83\n  - category English\n    value 71\n  - category English\n    value 77\n  - category Physics\n    value 58\n  - category Physics\n    value 72\n  - category Physics\n    value 85\n  - category Physics\n    value 63\n  - category Physics\n    value 90\n  - category Physics\n    value 68\n  - category Physics\n    value 78\n  - category Physics\n    value 55\n  - category Physics\n    value 82\n  - category Physics\n    value 70\n  - category Physics\n    value 92\n  - category Physics\n    value 65\n  - category Physics\n    value 76\n  - category Physics\n    value 60\n  - category Physics\n    value 88\n  - category Physics\n    value 74\n  - category Physics\n    value 80\n  - category Physics\n    value 67\n  - category Physics\n    value 83\n  - category Physics\n    value 62\n  - category Physics\n    value 75\ntitle "Exam Scores by Subject"\naxisXTitle Subject\naxisYTitle Score',
    },
    {
      title: 'Penguin Flipper Length Distribution (Grouped by Species and Sex, Custom Colors)',
      description:
        'Penguin Flipper Length Distribution (Grouped by Species and Sex): Comparison of male and female flipper length (mm) across Adelie, Chinstrap, and Gentoo penguins.',
      json: {
        type: 'boxplot',
        data: [
          { category: 'Adelie', group: 'MALE', value: 195 },
          { category: 'Adelie', group: 'MALE', value: 191 },
          { category: 'Adelie', group: 'MALE', value: 198 },
          { category: 'Adelie', group: 'MALE', value: 197 },
          { category: 'Adelie', group: 'MALE', value: 194 },
          { category: 'Adelie', group: 'MALE', value: 185 },
          { category: 'Adelie', group: 'MALE', value: 200 },
          { category: 'Adelie', group: 'MALE', value: 210 },
          { category: 'Adelie', group: 'FEMALE', value: 181 },
          { category: 'Adelie', group: 'FEMALE', value: 186 },
          { category: 'Adelie', group: 'FEMALE', value: 182 },
          { category: 'Adelie', group: 'FEMALE', value: 174 },
          { category: 'Adelie', group: 'FEMALE', value: 189 },
          { category: 'Adelie', group: 'FEMALE', value: 187 },
          { category: 'Adelie', group: 'FEMALE', value: 190 },
          { category: 'Chinstrap', group: 'MALE', value: 196 },
          { category: 'Chinstrap', group: 'MALE', value: 197 },
          { category: 'Chinstrap', group: 'MALE', value: 201 },
          { category: 'Chinstrap', group: 'MALE', value: 205 },
          { category: 'Chinstrap', group: 'MALE', value: 210 },
          { category: 'Chinstrap', group: 'MALE', value: 212 },
          { category: 'Chinstrap', group: 'FEMALE', value: 192 },
          { category: 'Chinstrap', group: 'FEMALE', value: 188 },
          { category: 'Chinstrap', group: 'FEMALE', value: 195 },
          { category: 'Chinstrap', group: 'FEMALE', value: 181 },
          { category: 'Chinstrap', group: 'FEMALE', value: 187 },
          { category: 'Chinstrap', group: 'FEMALE', value: 190 },
          { category: 'Gentoo', group: 'MALE', value: 230 },
          { category: 'Gentoo', group: 'MALE', value: 221 },
          { category: 'Gentoo', group: 'MALE', value: 225 },
          { category: 'Gentoo', group: 'MALE', value: 231 },
          { category: 'Gentoo', group: 'MALE', value: 228 },
          { category: 'Gentoo', group: 'FEMALE', value: 211 },
          { category: 'Gentoo', group: 'FEMALE', value: 210 },
          { category: 'Gentoo', group: 'FEMALE', value: 214 },
          { category: 'Gentoo', group: 'FEMALE', value: 213 },
          { category: 'Gentoo', group: 'FEMALE', value: 219 },
        ],
        title: 'Penguin Flipper Length Distribution (by Species and Sex)',
        axisYTitle: 'Flipper Length (mm)',
        style: {
          palette: ['#A855F7', '#38BDF8', '#F9A8D4', '#34D399'],
          backgroundColor: '#f8f7ff',
        },
      },
      dsl: 'vis boxplot\ndata\n  - category Adelie\n    group MALE\n    value 195\n  - category Adelie\n    group MALE\n    value 191\n  - category Adelie\n    group MALE\n    value 198\n  - category Adelie\n    group MALE\n    value 197\n  - category Adelie\n    group MALE\n    value 194\n  - category Adelie\n    group MALE\n    value 185\n  - category Adelie\n    group MALE\n    value 200\n  - category Adelie\n    group MALE\n    value 210\n  - category Adelie\n    group FEMALE\n    value 181\n  - category Adelie\n    group FEMALE\n    value 186\n  - category Adelie\n    group FEMALE\n    value 182\n  - category Adelie\n    group FEMALE\n    value 174\n  - category Adelie\n    group FEMALE\n    value 189\n  - category Adelie\n    group FEMALE\n    value 187\n  - category Adelie\n    group FEMALE\n    value 190\n  - category Chinstrap\n    group MALE\n    value 196\n  - category Chinstrap\n    group MALE\n    value 197\n  - category Chinstrap\n    group MALE\n    value 201\n  - category Chinstrap\n    group MALE\n    value 205\n  - category Chinstrap\n    group MALE\n    value 210\n  - category Chinstrap\n    group MALE\n    value 212\n  - category Chinstrap\n    group FEMALE\n    value 192\n  - category Chinstrap\n    group FEMALE\n    value 188\n  - category Chinstrap\n    group FEMALE\n    value 195\n  - category Chinstrap\n    group FEMALE\n    value 181\n  - category Chinstrap\n    group FEMALE\n    value 187\n  - category Chinstrap\n    group FEMALE\n    value 190\n  - category Gentoo\n    group MALE\n    value 230\n  - category Gentoo\n    group MALE\n    value 221\n  - category Gentoo\n    group MALE\n    value 225\n  - category Gentoo\n    group MALE\n    value 231\n  - category Gentoo\n    group MALE\n    value 228\n  - category Gentoo\n    group FEMALE\n    value 211\n  - category Gentoo\n    group FEMALE\n    value 210\n  - category Gentoo\n    group FEMALE\n    value 214\n  - category Gentoo\n    group FEMALE\n    value 213\n  - category Gentoo\n    group FEMALE\n    value 219\ntitle "Penguin Flipper Length Distribution (by Species and Sex)"\naxisYTitle "Flipper Length (mm)"\nstyle\n  palette\n    - "#A855F7"\n    - "#38BDF8"\n    - "#F9A8D4"\n    - "#34D399"\n  backgroundColor "#f8f7ff"',
    },
    {
      title:
        'Air Quality Index Distribution of Five Cities: 25 AQI samples each from Beijing, Shanghai, Guangzhou, Chengdu, and Shenzhen, Custom Palette',
      description:
        'Air Quality Index Distribution of Five Cities: 25 AQI samples each from Beijing, Shanghai, Guangzhou, Chengdu, and Shenzhen.',
      json: {
        type: 'boxplot',
        data: [
          { category: 'Beijing', value: 85 },
          { category: 'Beijing', value: 120 },
          { category: 'Beijing', value: 95 },
          { category: 'Beijing', value: 150 },
          { category: 'Beijing', value: 78 },
          { category: 'Beijing', value: 110 },
          { category: 'Beijing', value: 88 },
          { category: 'Beijing', value: 135 },
          { category: 'Beijing', value: 72 },
          { category: 'Beijing', value: 105 },
          { category: 'Beijing', value: 92 },
          { category: 'Beijing', value: 125 },
          { category: 'Beijing', value: 68 },
          { category: 'Beijing', value: 115 },
          { category: 'Beijing', value: 82 },
          { category: 'Beijing', value: 140 },
          { category: 'Beijing', value: 76 },
          { category: 'Beijing', value: 100 },
          { category: 'Beijing', value: 90 },
          { category: 'Beijing', value: 130 },
          { category: 'Beijing', value: 65 },
          { category: 'Beijing', value: 108 },
          { category: 'Beijing', value: 86 },
          { category: 'Beijing', value: 145 },
          { category: 'Beijing', value: 74 },
          { category: 'Shanghai', value: 62 },
          { category: 'Shanghai', value: 85 },
          { category: 'Shanghai', value: 70 },
          { category: 'Shanghai', value: 95 },
          { category: 'Shanghai', value: 58 },
          { category: 'Shanghai', value: 80 },
          { category: 'Shanghai', value: 68 },
          { category: 'Shanghai', value: 90 },
          { category: 'Shanghai', value: 55 },
          { category: 'Shanghai', value: 75 },
          { category: 'Shanghai', value: 72 },
          { category: 'Shanghai', value: 88 },
          { category: 'Shanghai', value: 52 },
          { category: 'Shanghai', value: 82 },
          { category: 'Shanghai', value: 65 },
          { category: 'Shanghai', value: 92 },
          { category: 'Shanghai', value: 60 },
          { category: 'Shanghai', value: 78 },
          { category: 'Shanghai', value: 70 },
          { category: 'Shanghai', value: 86 },
          { category: 'Shanghai', value: 50 },
          { category: 'Shanghai', value: 76 },
          { category: 'Shanghai', value: 64 },
          { category: 'Guangzhou', value: 45 },
          { category: 'Guangzhou', value: 68 },
          { category: 'Guangzhou', value: 55 },
          { category: 'Guangzhou', value: 78 },
          { category: 'Guangzhou', value: 42 },
          { category: 'Guangzhou', value: 62 },
          { category: 'Guangzhou', value: 50 },
          { category: 'Guangzhou', value: 72 },
          { category: 'Guangzhou', value: 38 },
          { category: 'Guangzhou', value: 58 },
          { category: 'Guangzhou', value: 52 },
          { category: 'Guangzhou', value: 70 },
          { category: 'Guangzhou', value: 40 },
          { category: 'Guangzhou', value: 65 },
          { category: 'Guangzhou', value: 48 },
          { category: 'Guangzhou', value: 75 },
          { category: 'Guangzhou', value: 44 },
          { category: 'Guangzhou', value: 60 },
          { category: 'Guangzhou', value: 53 },
          { category: 'Guangzhou', value: 68 },
          { category: 'Guangzhou', value: 36 },
          { category: 'Guangzhou', value: 56 },
          { category: 'Guangzhou', value: 46 },
          { category: 'Guangzhou', value: 72 },
          { category: 'Guangzhou', value: 50 },
          { category: 'Chengdu', value: 70 },
          { category: 'Chengdu', value: 95 },
          { category: 'Chengdu', value: 80 },
          { category: 'Chengdu', value: 110 },
          { category: 'Chengdu', value: 65 },
          { category: 'Chengdu', value: 88 },
          { category: 'Chengdu', value: 75 },
          { category: 'Chengdu', value: 100 },
          { category: 'Chengdu', value: 60 },
          { category: 'Chengdu', value: 82 },
          { category: 'Chengdu', value: 78 },
          { category: 'Chengdu', value: 92 },
          { category: 'Chengdu', value: 58 },
          { category: 'Chengdu', value: 85 },
          { category: 'Chengdu', value: 72 },
          { category: 'Chengdu', value: 105 },
          { category: 'Chengdu', value: 68 },
          { category: 'Chengdu', value: 90 },
          { category: 'Chengdu', value: 76 },
          { category: 'Chengdu', value: 98 },
          { category: 'Chengdu', value: 55 },
          { category: 'Chengdu', value: 82 },
          { category: 'Chengdu', value: 70 },
          { category: 'Chengdu', value: 108 },
          { category: 'Chengdu', value: 64 },
          { category: 'Shenzhen', value: 40 },
          { category: 'Shenzhen', value: 60 },
          { category: 'Shenzhen', value: 48 },
          { category: 'Shenzhen', value: 70 },
          { category: 'Shenzhen', value: 35 },
          { category: 'Shenzhen', value: 55 },
          { category: 'Shenzhen', value: 45 },
          { category: 'Shenzhen', value: 65 },
          { category: 'Shenzhen', value: 32 },
          { category: 'Shenzhen', value: 52 },
          { category: 'Shenzhen', value: 48 },
          { category: 'Shenzhen', value: 62 },
          { category: 'Shenzhen', value: 38 },
          { category: 'Shenzhen', value: 58 },
          { category: 'Shenzhen', value: 42 },
          { category: 'Shenzhen', value: 68 },
          { category: 'Shenzhen', value: 36 },
          { category: 'Shenzhen', value: 50 },
          { category: 'Shenzhen', value: 46 },
          { category: 'Shenzhen', value: 60 },
          { category: 'Shenzhen', value: 30 },
          { category: 'Shenzhen', value: 55 },
          { category: 'Shenzhen', value: 44 },
          { category: 'Shenzhen', value: 65 },
          { category: 'Shenzhen', value: 40 },
        ],
        title: 'Air Quality Index Distribution of Five Cities',
        axisXTitle: 'City',
        axisYTitle: 'AQI',
        theme: 'academy',
        style: {
          palette: ['#C45B42', '#7D8C6E', '#D4A373', '#E9C46A', '#A98467'],
          backgroundColor: '#FBF8F4',
        },
      },
      dsl: 'vis boxplot\ndata\n  - category Beijing\n    value 85\n  - category Beijing\n    value 120\n  - category Beijing\n    value 95\n  - category Beijing\n    value 150\n  - category Beijing\n    value 78\n  - category Beijing\n    value 110\n  - category Beijing\n    value 88\n  - category Beijing\n    value 135\n  - category Beijing\n    value 72\n  - category Beijing\n    value 105\n  - category Beijing\n    value 92\n  - category Beijing\n    value 125\n  - category Beijing\n    value 68\n  - category Beijing\n    value 115\n  - category Beijing\n    value 82\n  - category Beijing\n    value 140\n  - category Beijing\n    value 76\n  - category Beijing\n    value 100\n  - category Beijing\n    value 90\n  - category Beijing\n    value 130\n  - category Beijing\n    value 65\n  - category Beijing\n    value 108\n  - category Beijing\n    value 86\n  - category Beijing\n    value 145\n  - category Beijing\n    value 74\n  - category Shanghai\n    value 62\n  - category Shanghai\n    value 85\n  - category Shanghai\n    value 70\n  - category Shanghai\n    value 95\n  - category Shanghai\n    value 58\n  - category Shanghai\n    value 80\n  - category Shanghai\n    value 68\n  - category Shanghai\n    value 90\n  - category Shanghai\n    value 55\n  - category Shanghai\n    value 75\n  - category Shanghai\n    value 72\n  - category Shanghai\n    value 88\n  - category Shanghai\n    value 52\n  - category Shanghai\n    value 82\n  - category Shanghai\n    value 65\n  - category Shanghai\n    value 92\n  - category Shanghai\n    value 60\n  - category Shanghai\n    value 78\n  - category Shanghai\n    value 70\n  - category Shanghai\n    value 86\n  - category Shanghai\n    value 50\n  - category Shanghai\n    value 76\n  - category Shanghai\n    value 64\n  - category Guangzhou\n    value 45\n  - category Guangzhou\n    value 68\n  - category Guangzhou\n    value 55\n  - category Guangzhou\n    value 78\n  - category Guangzhou\n    value 42\n  - category Guangzhou\n    value 62\n  - category Guangzhou\n    value 50\n  - category Guangzhou\n    value 72\n  - category Guangzhou\n    value 38\n  - category Guangzhou\n    value 58\n  - category Guangzhou\n    value 52\n  - category Guangzhou\n    value 70\n  - category Guangzhou\n    value 40\n  - category Guangzhou\n    value 65\n  - category Guangzhou\n    value 48\n  - category Guangzhou\n    value 75\n  - category Guangzhou\n    value 44\n  - category Guangzhou\n    value 60\n  - category Guangzhou\n    value 53\n  - category Guangzhou\n    value 68\n  - category Guangzhou\n    value 36\n  - category Guangzhou\n    value 56\n  - category Guangzhou\n    value 46\n  - category Guangzhou\n    value 72\n  - category Guangzhou\n    value 50\n  - category Chengdu\n    value 70\n  - category Chengdu\n    value 95\n  - category Chengdu\n    value 80\n  - category Chengdu\n    value 110\n  - category Chengdu\n    value 65\n  - category Chengdu\n    value 88\n  - category Chengdu\n    value 75\n  - category Chengdu\n    value 100\n  - category Chengdu\n    value 60\n  - category Chengdu\n    value 82\n  - category Chengdu\n    value 78\n  - category Chengdu\n    value 92\n  - category Chengdu\n    value 58\n  - category Chengdu\n    value 85\n  - category Chengdu\n    value 72\n  - category Chengdu\n    value 105\n  - category Chengdu\n    value 68\n  - category Chengdu\n    value 90\n  - category Chengdu\n    value 76\n  - category Chengdu\n    value 98\n  - category Chengdu\n    value 55\n  - category Chengdu\n    value 82\n  - category Chengdu\n    value 70\n  - category Chengdu\n    value 108\n  - category Chengdu\n    value 64\n  - category Shenzhen\n    value 40\n  - category Shenzhen\n    value 60\n  - category Shenzhen\n    value 48\n  - category Shenzhen\n    value 70\n  - category Shenzhen\n    value 35\n  - category Shenzhen\n    value 55\n  - category Shenzhen\n    value 45\n  - category Shenzhen\n    value 65\n  - category Shenzhen\n    value 32\n  - category Shenzhen\n    value 52\n  - category Shenzhen\n    value 48\n  - category Shenzhen\n    value 62\n  - category Shenzhen\n    value 38\n  - category Shenzhen\n    value 58\n  - category Shenzhen\n    value 42\n  - category Shenzhen\n    value 68\n  - category Shenzhen\n    value 36\n  - category Shenzhen\n    value 50\n  - category Shenzhen\n    value 46\n  - category Shenzhen\n    value 60\n  - category Shenzhen\n    value 30\n  - category Shenzhen\n    value 55\n  - category Shenzhen\n    value 44\n  - category Shenzhen\n    value 65\n  - category Shenzhen\n    value 40\ntitle "Air Quality Index Distribution of Five Cities"\naxisXTitle City\naxisYTitle AQI\ntheme academy\nstyle\n  palette\n    - "#C45B42"\n    - "#7D8C6E"\n    - "#D4A373"\n    - "#E9C46A"\n    - "#A98467"\n  backgroundColor "#FBF8F4"',
    },
  ],
};
