export const violinChartData = {
  id: 'violin-chart',
  name: 'Violin Chart',
  galleryDsl:
    'vis violin\ndata\n  - category "I. setosa"\n    value 5.1\n  - category "I. setosa"\n    value 4.9\n  - category "I. setosa"\n    value 4.7\n  - category "I. setosa"\n    value 4.6\n  - category "I. setosa"\n    value 5.0\n  - category "I. setosa"\n    value 5.4\n  - category "I. setosa"\n    value 4.6\n  - category "I. setosa"\n    value 5.0\n  - category "I. setosa"\n    value 4.4\n  - category "I. setosa"\n    value 4.9\n  - category "I. setosa"\n    value 5.4\n  - category "I. setosa"\n    value 4.8\n  - category "I. setosa"\n    value 4.8\n  - category "I. setosa"\n    value 4.3\n  - category "I. setosa"\n    value 5.8\n  - category "I. versicolor"\n    value 7.0\n  - category "I. versicolor"\n    value 6.4\n  - category "I. versicolor"\n    value 6.9\n  - category "I. versicolor"\n    value 5.5\n  - category "I. versicolor"\n    value 6.5\n  - category "I. versicolor"\n    value 5.7\n  - category "I. versicolor"\n    value 6.3\n  - category "I. versicolor"\n    value 4.9\n  - category "I. versicolor"\n    value 6.6\n  - category "I. versicolor"\n    value 5.2\n  - category "I. versicolor"\n    value 5.0\n  - category "I. versicolor"\n    value 5.9\n  - category "I. versicolor"\n    value 6.0\n  - category "I. versicolor"\n    value 6.1\n  - category "I. virginica"\n    value 6.3\n  - category "I. virginica"\n    value 5.8\n  - category "I. virginica"\n    value 7.1\n  - category "I. virginica"\n    value 6.3\n  - category "I. virginica"\n    value 6.5\n  - category "I. virginica"\n    value 7.6\n  - category "I. virginica"\n    value 4.9\n  - category "I. virginica"\n    value 7.3\n  - category "I. virginica"\n    value 6.7\n  - category "I. virginica"\n    value 7.2\n  - category "I. virginica"\n    value 6.5\n  - category "I. virginica"\n    value 6.4\n  - category "I. virginica"\n    value 6.8\n  - category "I. virginica"\n    value 5.7\ntitle "Iris Sepal Length by Species"\naxisYTitle "Sepal (cm)"',
  galleryJson: {
    type: 'violin',
    data: [
      { category: 'I. setosa', value: 5.1 },
      { category: 'I. setosa', value: 4.9 },
      { category: 'I. setosa', value: 4.7 },
      { category: 'I. setosa', value: 4.6 },
      { category: 'I. setosa', value: 5 },
      { category: 'I. setosa', value: 5.4 },
      { category: 'I. setosa', value: 4.6 },
      { category: 'I. setosa', value: 5 },
      { category: 'I. setosa', value: 4.4 },
      { category: 'I. setosa', value: 4.9 },
      { category: 'I. setosa', value: 5.4 },
      { category: 'I. setosa', value: 4.8 },
      { category: 'I. setosa', value: 4.8 },
      { category: 'I. setosa', value: 4.3 },
      { category: 'I. setosa', value: 5.8 },
      { category: 'I. versicolor', value: 7 },
      { category: 'I. versicolor', value: 6.4 },
      { category: 'I. versicolor', value: 6.9 },
      { category: 'I. versicolor', value: 5.5 },
      { category: 'I. versicolor', value: 6.5 },
      { category: 'I. versicolor', value: 5.7 },
      { category: 'I. versicolor', value: 6.3 },
      { category: 'I. versicolor', value: 4.9 },
      { category: 'I. versicolor', value: 6.6 },
      { category: 'I. versicolor', value: 5.2 },
      { category: 'I. versicolor', value: 5 },
      { category: 'I. versicolor', value: 5.9 },
      { category: 'I. versicolor', value: 6 },
      { category: 'I. versicolor', value: 6.1 },
      { category: 'I. virginica', value: 6.3 },
      { category: 'I. virginica', value: 5.8 },
      { category: 'I. virginica', value: 7.1 },
      { category: 'I. virginica', value: 6.3 },
      { category: 'I. virginica', value: 6.5 },
      { category: 'I. virginica', value: 7.6 },
      { category: 'I. virginica', value: 4.9 },
      { category: 'I. virginica', value: 7.3 },
      { category: 'I. virginica', value: 6.7 },
      { category: 'I. virginica', value: 7.2 },
      { category: 'I. virginica', value: 6.5 },
      { category: 'I. virginica', value: 6.4 },
      { category: 'I. virginica', value: 6.8 },
      { category: 'I. virginica', value: 5.7 },
    ],
    title: 'Iris Sepal Length by Species',
    axisYTitle: 'Sepal (cm)',
  },
  description:
    'A violin chart is a statistical chart used to display data distribution and probability density. It uses symmetric density curves to show the distribution shape of data, and can combine boxplot elements to display median and quartiles. It is suitable for intuitively comparing the distribution and density characteristics of different groups of data.',
  knowledge: {
    introduction:
      'A violin chart is a statistical chart used to display data distribution and probability density. It uses symmetric density curves to show the distribution shape of data, and can combine boxplot elements to display median and quartiles. It is suitable for intuitively comparing the distribution and density characteristics of different groups of data.',
    useCases: [
      'Used to display the distribution and density of one or more groups of data, such as score distributions, experimental results, financial data, etc.',
      'Suitable for highlighting data distribution shapes, central tendencies, and outliers',
    ],
    config: [
      {
        name: 'Configuration Options',
        config: [
          {
            property: 'type',
            type: 'required',
            valueType: 'string',
            description: 'Value must be "violin".',
          },
          {
            property: 'data',
            type: 'required',
            valueType: 'Object[]',
            description: 'Chart data.',
          },
          {
            property: 'data.category',
            type: 'required',
            valueType: 'string',
            description: 'Category name.',
          },
          {
            property: 'data.value',
            type: 'required',
            valueType: 'number',
            description: 'Category value.',
          },
          {
            property: 'data.group',
            type: 'optional',
            valueType: 'string',
            description: 'Group name, used for multi-group data comparison.',
          },
          {
            property: 'title',
            type: 'optional',
            valueType: 'string',
            description: 'Chart title.',
          },
          {
            property: 'axisXTitle',
            type: 'optional',
            valueType: 'string',
            description: 'X-axis title.',
          },
          {
            property: 'axisYTitle',
            type: 'optional',
            valueType: 'string',
            description: 'Y-axis title.',
          },
          {
            property: 'theme',
            type: 'optional',
            valueType: "'default' | 'dark' | 'academy'",
            description: 'Chart theme, default is "default".',
          },
          {
            property: 'style',
            type: 'optional',
            valueType: 'Object',
            description: 'Chart style.',
          },
          {
            property: 'style.palette',
            type: 'optional',
            valueType: 'string[]',
            description: 'Must be an array of valid color values.',
          },
          {
            property: 'style.backgroundColor',
            type: 'optional',
            valueType: 'string',
            description: 'Must be a valid color value.',
          },
          {
            property: 'style.startAtZero',
            type: 'optional',
            valueType: 'boolean',
            description: 'Whether the Y-axis starts from zero, default is false.',
          },
          {
            property: 'axisXTitle',
            type: 'optional',
            valueType: 'string',
            description: 'X-axis title.',
          },
          {
            property: 'axisYTitle',
            type: 'optional',
            valueType: 'string',
            description: 'Y-axis title.',
          },
        ],
      },
    ],
  },
  examples: [
    {
      title: 'Iris Sepal Length Distribution (Grouped by Species)',
      description:
        'Iris Sepal Length Distribution (Grouped by Species): Comparison of sepal length (cm) across I. setosa, I. versicolor, and I. virginica.',
      json: {
        type: 'violin',
        data: [
          { category: 'I. setosa', value: 5.1 },
          { category: 'I. setosa', value: 4.9 },
          { category: 'I. setosa', value: 4.7 },
          { category: 'I. setosa', value: 4.6 },
          { category: 'I. setosa', value: 5 },
          { category: 'I. setosa', value: 5.4 },
          { category: 'I. setosa', value: 4.6 },
          { category: 'I. setosa', value: 5 },
          { category: 'I. setosa', value: 4.4 },
          { category: 'I. setosa', value: 4.9 },
          { category: 'I. setosa', value: 5.4 },
          { category: 'I. setosa', value: 4.8 },
          { category: 'I. setosa', value: 4.8 },
          { category: 'I. setosa', value: 4.3 },
          { category: 'I. setosa', value: 5.8 },
          { category: 'I. versicolor', value: 7 },
          { category: 'I. versicolor', value: 6.4 },
          { category: 'I. versicolor', value: 6.9 },
          { category: 'I. versicolor', value: 5.5 },
          { category: 'I. versicolor', value: 6.5 },
          { category: 'I. versicolor', value: 5.7 },
          { category: 'I. versicolor', value: 6.3 },
          { category: 'I. versicolor', value: 4.9 },
          { category: 'I. versicolor', value: 6.6 },
          { category: 'I. versicolor', value: 5.2 },
          { category: 'I. versicolor', value: 5 },
          { category: 'I. versicolor', value: 5.9 },
          { category: 'I. versicolor', value: 6 },
          { category: 'I. versicolor', value: 6.1 },
          { category: 'I. virginica', value: 6.3 },
          { category: 'I. virginica', value: 5.8 },
          { category: 'I. virginica', value: 7.1 },
          { category: 'I. virginica', value: 6.3 },
          { category: 'I. virginica', value: 6.5 },
          { category: 'I. virginica', value: 7.6 },
          { category: 'I. virginica', value: 4.9 },
          { category: 'I. virginica', value: 7.3 },
          { category: 'I. virginica', value: 6.7 },
          { category: 'I. virginica', value: 7.2 },
          { category: 'I. virginica', value: 6.5 },
          { category: 'I. virginica', value: 6.4 },
          { category: 'I. virginica', value: 6.8 },
          { category: 'I. virginica', value: 5.7 },
        ],
        title: 'Iris Sepal Length Distribution',
        axisYTitle: 'Sepal (cm)',
      },
      dsl: 'vis violin\ndata\n  - category "I. setosa"\n    value 5.1\n  - category "I. setosa"\n    value 4.9\n  - category "I. setosa"\n    value 4.7\n  - category "I. setosa"\n    value 4.6\n  - category "I. setosa"\n    value 5.0\n  - category "I. setosa"\n    value 5.4\n  - category "I. setosa"\n    value 4.6\n  - category "I. setosa"\n    value 5.0\n  - category "I. setosa"\n    value 4.4\n  - category "I. setosa"\n    value 4.9\n  - category "I. setosa"\n    value 5.4\n  - category "I. setosa"\n    value 4.8\n  - category "I. setosa"\n    value 4.8\n  - category "I. setosa"\n    value 4.3\n  - category "I. setosa"\n    value 5.8\n  - category "I. versicolor"\n    value 7.0\n  - category "I. versicolor"\n    value 6.4\n  - category "I. versicolor"\n    value 6.9\n  - category "I. versicolor"\n    value 5.5\n  - category "I. versicolor"\n    value 6.5\n  - category "I. versicolor"\n    value 5.7\n  - category "I. versicolor"\n    value 6.3\n  - category "I. versicolor"\n    value 4.9\n  - category "I. versicolor"\n    value 6.6\n  - category "I. versicolor"\n    value 5.2\n  - category "I. versicolor"\n    value 5.0\n  - category "I. versicolor"\n    value 5.9\n  - category "I. versicolor"\n    value 6.0\n  - category "I. versicolor"\n    value 6.1\n  - category "I. virginica"\n    value 6.3\n  - category "I. virginica"\n    value 5.8\n  - category "I. virginica"\n    value 7.1\n  - category "I. virginica"\n    value 6.3\n  - category "I. virginica"\n    value 6.5\n  - category "I. virginica"\n    value 7.6\n  - category "I. virginica"\n    value 4.9\n  - category "I. virginica"\n    value 7.3\n  - category "I. virginica"\n    value 6.7\n  - category "I. virginica"\n    value 7.2\n  - category "I. virginica"\n    value 6.5\n  - category "I. virginica"\n    value 6.4\n  - category "I. virginica"\n    value 6.8\n  - category "I. virginica"\n    value 5.7\ntitle "Iris Sepal Length Distribution"\naxisYTitle "Sepal (cm)"',
    },
    {
      title:
        'Temperature Distribution of Four Cities: Beijing, Shanghai, Guangzhou, Harbin (30 samples each), Custom Colors',
      description:
        'Temperature Distribution of Four Cities: Beijing, Shanghai, Guangzhou, Harbin (30 samples each)',
      json: {
        type: 'violin',
        data: [
          { category: 'Beijing', value: -2 },
          { category: 'Beijing', value: 5 },
          { category: 'Beijing', value: 15 },
          { category: 'Beijing', value: 25 },
          { category: 'Beijing', value: 30 },
          { category: 'Beijing', value: 28 },
          { category: 'Beijing', value: 20 },
          { category: 'Beijing', value: 10 },
          { category: 'Beijing', value: 0 },
          { category: 'Beijing', value: -5 },
          { category: 'Beijing', value: 8 },
          { category: 'Beijing', value: 18 },
          { category: 'Beijing', value: 26 },
          { category: 'Beijing', value: 32 },
          { category: 'Beijing', value: 22 },
          { category: 'Beijing', value: 12 },
          { category: 'Beijing', value: 3 },
          { category: 'Beijing', value: -3 },
          { category: 'Beijing', value: 16 },
          { category: 'Beijing', value: 27 },
          { category: 'Beijing', value: 29 },
          { category: 'Beijing', value: 14 },
          { category: 'Beijing', value: 6 },
          { category: 'Beijing', value: -1 },
          { category: 'Beijing', value: 24 },
          { category: 'Beijing', value: 19 },
          { category: 'Beijing', value: 9 },
          { category: 'Beijing', value: 1 },
          { category: 'Beijing', value: 31 },
          { category: 'Beijing', value: 21 },
          { category: 'Shanghai', value: 5 },
          { category: 'Shanghai', value: 10 },
          { category: 'Shanghai', value: 18 },
          { category: 'Shanghai', value: 25 },
          { category: 'Shanghai', value: 30 },
          { category: 'Shanghai', value: 28 },
          { category: 'Shanghai', value: 22 },
          { category: 'Shanghai', value: 15 },
          { category: 'Shanghai', value: 8 },
          { category: 'Shanghai', value: 2 },
          { category: 'Shanghai', value: 12 },
          { category: 'Shanghai', value: 20 },
          { category: 'Shanghai', value: 27 },
          { category: 'Shanghai', value: 32 },
          { category: 'Shanghai', value: 24 },
          { category: 'Shanghai', value: 16 },
          { category: 'Shanghai', value: 7 },
          { category: 'Shanghai', value: 3 },
          { category: 'Shanghai', value: 19 },
          { category: 'Shanghai', value: 26 },
          { category: 'Shanghai', value: 29 },
          { category: 'Shanghai', value: 14 },
          { category: 'Shanghai', value: 9 },
          { category: 'Shanghai', value: 4 },
          { category: 'Shanghai', value: 23 },
          { category: 'Shanghai', value: 21 },
          { category: 'Shanghai', value: 11 },
          { category: 'Shanghai', value: 6 },
          { category: 'Shanghai', value: 31 },
          { category: 'Shanghai', value: 17 },
          { category: 'Guangzhou', value: 15 },
          { category: 'Guangzhou', value: 18 },
          { category: 'Guangzhou', value: 22 },
          { category: 'Guangzhou', value: 27 },
          { category: 'Guangzhou', value: 30 },
          { category: 'Guangzhou', value: 29 },
          { category: 'Guangzhou', value: 25 },
          { category: 'Guangzhou', value: 20 },
          { category: 'Guangzhou', value: 16 },
          { category: 'Guangzhou', value: 12 },
          { category: 'Guangzhou', value: 19 },
          { category: 'Guangzhou', value: 23 },
          { category: 'Guangzhou', value: 28 },
          { category: 'Guangzhou', value: 31 },
          { category: 'Guangzhou', value: 26 },
          { category: 'Guangzhou', value: 21 },
          { category: 'Guangzhou', value: 17 },
          { category: 'Guangzhou', value: 13 },
          { category: 'Guangzhou', value: 24 },
          { category: 'Guangzhou', value: 27 },
          { category: 'Guangzhou', value: 30 },
          { category: 'Guangzhou', value: 20 },
          { category: 'Guangzhou', value: 16 },
          { category: 'Guangzhou', value: 14 },
          { category: 'Guangzhou', value: 25 },
          { category: 'Guangzhou', value: 22 },
          { category: 'Guangzhou', value: 18 },
          { category: 'Guangzhou', value: 15 },
          { category: 'Guangzhou', value: 32 },
          { category: 'Guangzhou', value: 19 },
          { category: 'Harbin', value: -18 },
          { category: 'Harbin', value: -10 },
          { category: 'Harbin', value: 0 },
          { category: 'Harbin', value: 12 },
          { category: 'Harbin', value: 22 },
          { category: 'Harbin', value: 25 },
          { category: 'Harbin', value: 18 },
          { category: 'Harbin', value: 5 },
          { category: 'Harbin', value: -8 },
          { category: 'Harbin', value: -20 },
          { category: 'Harbin', value: -5 },
          { category: 'Harbin', value: 8 },
          { category: 'Harbin', value: 15 },
          { category: 'Harbin', value: 24 },
          { category: 'Harbin', value: 20 },
          { category: 'Harbin', value: 2 },
          { category: 'Harbin', value: -12 },
          { category: 'Harbin', value: -15 },
          { category: 'Harbin', value: 10 },
          { category: 'Harbin', value: 23 },
          { category: 'Harbin', value: 26 },
          { category: 'Harbin', value: 16 },
          { category: 'Harbin', value: -3 },
          { category: 'Harbin', value: -8 },
          { category: 'Harbin', value: -22 },
          { category: 'Harbin', value: 14 },
          { category: 'Harbin', value: 6 },
          { category: 'Harbin', value: -2 },
          { category: 'Harbin', value: 19 },
          { category: 'Harbin', value: 21 },
          { category: 'Harbin', value: 3 },
        ],
        title: 'Four-City Temperature Distribution',
        axisYTitle: 'Temperature (°C)',
        style: {
          palette: ['#A855F7', '#38BDF8', '#F9A8D4', '#34D399'],
          backgroundColor: '#f8f7ff',
        },
      },
      dsl: 'vis violin\ndata\n  - category Beijing\n    value -2\n  - category Beijing\n    value 5\n  - category Beijing\n    value 15\n  - category Beijing\n    value 25\n  - category Beijing\n    value 30\n  - category Beijing\n    value 28\n  - category Beijing\n    value 20\n  - category Beijing\n    value 10\n  - category Beijing\n    value 0\n  - category Beijing\n    value -5\n  - category Beijing\n    value 8\n  - category Beijing\n    value 18\n  - category Beijing\n    value 26\n  - category Beijing\n    value 32\n  - category Beijing\n    value 22\n  - category Beijing\n    value 12\n  - category Beijing\n    value 3\n  - category Beijing\n    value -3\n  - category Beijing\n    value 16\n  - category Beijing\n    value 27\n  - category Beijing\n    value 29\n  - category Beijing\n    value 14\n  - category Beijing\n    value 6\n  - category Beijing\n    value -1\n  - category Beijing\n    value 24\n  - category Beijing\n    value 19\n  - category Beijing\n    value 9\n  - category Beijing\n    value 1\n  - category Beijing\n    value 31\n  - category Beijing\n    value 21\n  - category Shanghai\n    value 5\n  - category Shanghai\n    value 10\n  - category Shanghai\n    value 18\n  - category Shanghai\n    value 25\n  - category Shanghai\n    value 30\n  - category Shanghai\n    value 28\n  - category Shanghai\n    value 22\n  - category Shanghai\n    value 15\n  - category Shanghai\n    value 8\n  - category Shanghai\n    value 2\n  - category Shanghai\n    value 12\n  - category Shanghai\n    value 20\n  - category Shanghai\n    value 27\n  - category Shanghai\n    value 32\n  - category Shanghai\n    value 24\n  - category Shanghai\n    value 16\n  - category Shanghai\n    value 7\n  - category Shanghai\n    value 3\n  - category Shanghai\n    value 19\n  - category Shanghai\n    value 26\n  - category Shanghai\n    value 29\n  - category Shanghai\n    value 14\n  - category Shanghai\n    value 9\n  - category Shanghai\n    value 4\n  - category Shanghai\n    value 23\n  - category Shanghai\n    value 21\n  - category Shanghai\n    value 11\n  - category Shanghai\n    value 6\n  - category Shanghai\n    value 31\n  - category Shanghai\n    value 17\n  - category Guangzhou\n    value 15\n  - category Guangzhou\n    value 18\n  - category Guangzhou\n    value 22\n  - category Guangzhou\n    value 27\n  - category Guangzhou\n    value 30\n  - category Guangzhou\n    value 29\n  - category Guangzhou\n    value 25\n  - category Guangzhou\n    value 20\n  - category Guangzhou\n    value 16\n  - category Guangzhou\n    value 12\n  - category Guangzhou\n    value 19\n  - category Guangzhou\n    value 23\n  - category Guangzhou\n    value 28\n  - category Guangzhou\n    value 31\n  - category Guangzhou\n    value 26\n  - category Guangzhou\n    value 21\n  - category Guangzhou\n    value 17\n  - category Guangzhou\n    value 13\n  - category Guangzhou\n    value 24\n  - category Guangzhou\n    value 27\n  - category Guangzhou\n    value 30\n  - category Guangzhou\n    value 20\n  - category Guangzhou\n    value 16\n  - category Guangzhou\n    value 14\n  - category Guangzhou\n    value 25\n  - category Guangzhou\n    value 22\n  - category Guangzhou\n    value 18\n  - category Guangzhou\n    value 15\n  - category Guangzhou\n    value 32\n  - category Guangzhou\n    value 19\n  - category Harbin\n    value -18\n  - category Harbin\n    value -10\n  - category Harbin\n    value 0\n  - category Harbin\n    value 12\n  - category Harbin\n    value 22\n  - category Harbin\n    value 25\n  - category Harbin\n    value 18\n  - category Harbin\n    value 5\n  - category Harbin\n    value -8\n  - category Harbin\n    value -20\n  - category Harbin\n    value -5\n  - category Harbin\n    value 8\n  - category Harbin\n    value 15\n  - category Harbin\n    value 24\n  - category Harbin\n    value 20\n  - category Harbin\n    value 2\n  - category Harbin\n    value -12\n  - category Harbin\n    value -15\n  - category Harbin\n    value 10\n  - category Harbin\n    value 23\n  - category Harbin\n    value 26\n  - category Harbin\n    value 16\n  - category Harbin\n    value -3\n  - category Harbin\n    value -8\n  - category Harbin\n    value -22\n  - category Harbin\n    value 14\n  - category Harbin\n    value 6\n  - category Harbin\n    value -2\n  - category Harbin\n    value 19\n  - category Harbin\n    value 21\n  - category Harbin\n    value 3\ntitle "Four-City Temperature Distribution"\naxisYTitle "Temperature (°C)"\nstyle\n  palette\n    - "#A855F7"\n    - "#38BDF8"\n    - "#F9A8D4"\n    - "#34D399"\n  backgroundColor "#f8f7ff"',
    },
    {
      title: 'Crop Yield Distribution: Rice, Wheat, Corn (25 samples each), Custom Palette',
      description: 'Crop Yield Distribution: Rice, Wheat, Corn (25 samples each)',
      json: {
        type: 'violin',
        data: [
          { category: 'Rice', value: 680 },
          { category: 'Rice', value: 720 },
          { category: 'Rice', value: 750 },
          { category: 'Rice', value: 690 },
          { category: 'Rice', value: 710 },
          { category: 'Rice', value: 760 },
          { category: 'Rice', value: 700 },
          { category: 'Rice', value: 730 },
          { category: 'Rice', value: 670 },
          { category: 'Rice', value: 740 },
          { category: 'Rice', value: 690 },
          { category: 'Rice', value: 720 },
          { category: 'Rice', value: 770 },
          { category: 'Rice', value: 680 },
          { category: 'Rice', value: 710 },
          { category: 'Rice', value: 750 },
          { category: 'Rice', value: 660 },
          { category: 'Rice', value: 730 },
          { category: 'Rice', value: 700 },
          { category: 'Rice', value: 760 },
          { category: 'Rice', value: 690 },
          { category: 'Rice', value: 720 },
          { category: 'Rice', value: 740 },
          { category: 'Rice', value: 680 },
          { category: 'Rice', value: 710 },
          { category: 'Wheat', value: 520 },
          { category: 'Wheat', value: 550 },
          { category: 'Wheat', value: 580 },
          { category: 'Wheat', value: 510 },
          { category: 'Wheat', value: 540 },
          { category: 'Wheat', value: 590 },
          { category: 'Wheat', value: 530 },
          { category: 'Wheat', value: 560 },
          { category: 'Wheat', value: 500 },
          { category: 'Wheat', value: 570 },
          { category: 'Wheat', value: 520 },
          { category: 'Wheat', value: 550 },
          { category: 'Wheat', value: 600 },
          { category: 'Wheat', value: 510 },
          { category: 'Wheat', value: 540 },
          { category: 'Wheat', value: 580 },
          { category: 'Wheat', value: 490 },
          { category: 'Wheat', value: 560 },
          { category: 'Wheat', value: 530 },
          { category: 'Wheat', value: 590 },
          { category: 'Wheat', value: 510 },
          { category: 'Wheat', value: 550 },
          { category: 'Wheat', value: 570 },
          { category: 'Wheat', value: 500 },
          { category: 'Wheat', value: 540 },
          { category: 'Corn', value: 620 },
          { category: 'Corn', value: 660 },
          { category: 'Corn', value: 700 },
          { category: 'Corn', value: 610 },
          { category: 'Corn', value: 650 },
          { category: 'Corn', value: 710 },
          { category: 'Corn', value: 630 },
          { category: 'Corn', value: 670 },
          { category: 'Corn', value: 600 },
          { category: 'Corn', value: 680 },
          { category: 'Corn', value: 620 },
          { category: 'Corn', value: 660 },
          { category: 'Corn', value: 720 },
          { category: 'Corn', value: 610 },
          { category: 'Corn', value: 650 },
          { category: 'Corn', value: 700 },
          { category: 'Corn', value: 590 },
          { category: 'Corn', value: 670 },
          { category: 'Corn', value: 640 },
          { category: 'Corn', value: 710 },
          { category: 'Corn', value: 620 },
          { category: 'Corn', value: 660 },
          { category: 'Corn', value: 690 },
          { category: 'Corn', value: 600 },
          { category: 'Corn', value: 650 },
        ],
        title: 'Crop Yield Distribution',
        axisYTitle: 'Yield (kg/acre)',
        theme: 'academy',
        style: { palette: ['#C45B42', '#7D8C6E', '#D4A373'], backgroundColor: '#FBF8F4' },
      },
      dsl: 'vis violin\ndata\n  - category Rice\n    value 680\n  - category Rice\n    value 720\n  - category Rice\n    value 750\n  - category Rice\n    value 690\n  - category Rice\n    value 710\n  - category Rice\n    value 760\n  - category Rice\n    value 700\n  - category Rice\n    value 730\n  - category Rice\n    value 670\n  - category Rice\n    value 740\n  - category Rice\n    value 690\n  - category Rice\n    value 720\n  - category Rice\n    value 770\n  - category Rice\n    value 680\n  - category Rice\n    value 710\n  - category Rice\n    value 750\n  - category Rice\n    value 660\n  - category Rice\n    value 730\n  - category Rice\n    value 700\n  - category Rice\n    value 760\n  - category Rice\n    value 690\n  - category Rice\n    value 720\n  - category Rice\n    value 740\n  - category Rice\n    value 680\n  - category Rice\n    value 710\n  - category Wheat\n    value 520\n  - category Wheat\n    value 550\n  - category Wheat\n    value 580\n  - category Wheat\n    value 510\n  - category Wheat\n    value 540\n  - category Wheat\n    value 590\n  - category Wheat\n    value 530\n  - category Wheat\n    value 560\n  - category Wheat\n    value 500\n  - category Wheat\n    value 570\n  - category Wheat\n    value 520\n  - category Wheat\n    value 550\n  - category Wheat\n    value 600\n  - category Wheat\n    value 510\n  - category Wheat\n    value 540\n  - category Wheat\n    value 580\n  - category Wheat\n    value 490\n  - category Wheat\n    value 560\n  - category Wheat\n    value 530\n  - category Wheat\n    value 590\n  - category Wheat\n    value 510\n  - category Wheat\n    value 550\n  - category Wheat\n    value 570\n  - category Wheat\n    value 500\n  - category Wheat\n    value 540\n  - category Corn\n    value 620\n  - category Corn\n    value 660\n  - category Corn\n    value 700\n  - category Corn\n    value 610\n  - category Corn\n    value 650\n  - category Corn\n    value 710\n  - category Corn\n    value 630\n  - category Corn\n    value 670\n  - category Corn\n    value 600\n  - category Corn\n    value 680\n  - category Corn\n    value 620\n  - category Corn\n    value 660\n  - category Corn\n    value 720\n  - category Corn\n    value 610\n  - category Corn\n    value 650\n  - category Corn\n    value 700\n  - category Corn\n    value 590\n  - category Corn\n    value 670\n  - category Corn\n    value 640\n  - category Corn\n    value 710\n  - category Corn\n    value 620\n  - category Corn\n    value 660\n  - category Corn\n    value 690\n  - category Corn\n    value 600\n  - category Corn\n    value 650\ntitle "Crop Yield Distribution"\naxisYTitle "Yield (kg/acre)"\ntheme academy\nstyle\n  palette\n    - "#C45B42"\n    - "#7D8C6E"\n    - "#D4A373"\n  backgroundColor "#FBF8F4"',
    },
  ],
};
