export const wordcloudData = {
  id: 'wordcloud',
  name: 'Word Cloud',
  galleryDsl:
    'vis word-cloud\ndata\n  - text "Machine Learning"\n    value 100\n  - text "Deep Learning"\n    value 95\n  - text "NLP"\n    value 88\n  - text "Computer Vision"\n    value 85\n  - text "LLM"\n    value 92\n  - text "Reinforcement Learning"\n    value 72\n  - text "Knowledge Graph"\n    value 65\n  - text "Data Mining"\n    value 70\n  - text "Neural Network"\n    value 80\n  - text "Transfer Learning"\n    value 60\n  - text "Generative AI"\n    value 90\n  - text "GAN"\n    value 55\n  - text "Attention Mechanism"\n    value 75\n  - text "Pre-training"\n    value 82\n  - text "Fine-tuning"\n    value 68\n  - text "Multimodal"\n    value 86\n  - text "Vector Database"\n    value 58\n  - text "Prompt Engineering"\n    value 78\n  - text "AI Agent"\n    value 84\n  - text "GNN"\n    value 50\n  - text "Bayesian"\n    value 45\n  - text "Federated Learning"\n    value 48\n  - text "Autonomous Driving"\n    value 76\n  - text "Speech Recognition"\n    value 62\n  - text "Recommendation System"\n    value 66\n  - text "Anomaly Detection"\n    value 42\n  - text "Time Series"\n    value 52\n  - text "Text Classification"\n    value 40\n  - text "Object Detection"\n    value 58\n  - text "Semantic Segmentation"\n    value 46\ntitle "AI Technology Keywords"',
  galleryJson: {
    type: 'word-cloud',
    data: [
      { text: 'Machine Learning', value: 100 },
      { text: 'Deep Learning', value: 95 },
      { text: 'NLP', value: 88 },
      { text: 'Computer Vision', value: 85 },
      { text: 'LLM', value: 92 },
      { text: 'Reinforcement Learning', value: 72 },
      { text: 'Knowledge Graph', value: 65 },
      { text: 'Data Mining', value: 70 },
      { text: 'Neural Network', value: 80 },
      { text: 'Transfer Learning', value: 60 },
      { text: 'Generative AI', value: 90 },
      { text: 'GAN', value: 55 },
      { text: 'Attention Mechanism', value: 75 },
      { text: 'Pre-training', value: 82 },
      { text: 'Fine-tuning', value: 68 },
      { text: 'Multimodal', value: 86 },
      { text: 'Vector Database', value: 58 },
      { text: 'Prompt Engineering', value: 78 },
      { text: 'AI Agent', value: 84 },
      { text: 'GNN', value: 50 },
      { text: 'Bayesian', value: 45 },
      { text: 'Federated Learning', value: 48 },
      { text: 'Autonomous Driving', value: 76 },
      { text: 'Speech Recognition', value: 62 },
      { text: 'Recommendation System', value: 66 },
      { text: 'Anomaly Detection', value: 42 },
      { text: 'Time Series', value: 52 },
      { text: 'Text Classification', value: 40 },
      { text: 'Object Detection', value: 58 },
      { text: 'Semantic Segmentation', value: 46 },
    ],
    title: 'AI Technology Keywords',
  },
  description:
    'A word cloud is a visualization method that displays the frequency or weight of words in text data, using different text sizes to represent word frequency. Word clouds help quickly identify the most commonly used or most important words in text data. The size of each word is typically proportional to its frequency — larger fonts represent more frequent or more important words, allowing users to intuitively see how often a word appears in the text. This visual approach enables users to quickly grasp the main content and core themes of the text.',
  knowledge: {
    introduction:
      'A word cloud is a visualization method that displays the frequency or weight of words in text data, using different text sizes to represent word frequency. Word clouds help quickly identify the most commonly used or most important words in text data. The size of each word is typically proportional to its frequency — larger fonts represent more frequent or more important words, allowing users to intuitively see how often a word appears in the text. This visual approach enables users to quickly grasp the main content and core themes of the text.',
    useCases: [
      'Analyze frequently used words in social media, reviews, or feedback.',
      'Identify keywords or topics in text analysis.',
      'Highlight the importance of specific terms, such as in news summaries or market research results.',
    ],
    config: [
      {
        name: 'Configuration Options',
        config: [
          {
            property: 'type',
            type: 'required',
            valueType: 'string',
            description: 'Value must be "word-cloud".',
          },
          {
            property: 'data',
            type: 'required',
            valueType: 'Object[]',
            description: 'Chart data.',
          },
          {
            property: 'data.text',
            type: 'required',
            valueType: 'string',
            description: 'The word to display in the word cloud.',
          },
          {
            property: 'data.value',
            type: 'required',
            valueType: 'number',
            description: 'Importance score of the word (frequency, weight, etc.).',
          },
          {
            property: 'title',
            type: 'optional',
            valueType: 'string',
            description: 'Chart title.',
          },
          {
            property: 'theme',
            type: 'optional',
            valueType: "'default' | 'dark' | 'academy'",
            description: 'Chart theme, default is "default".',
          },
          {
            property: 'style',
            type: 'optional',
            valueType: 'Object',
            description: 'Chart style.',
          },
          {
            property: 'style.backgroundColor',
            type: 'optional',
            valueType: 'string',
            description: 'Must be a valid color value.',
          },
          {
            property: 'style.palette',
            type: 'optional',
            valueType: 'string[]',
            description: 'Must be a valid color array.',
          },
        ],
      },
    ],
  },
  examples: [
    {
      title: 'Display the weight distribution of keywords in the AI technology field.',
      description: 'Display the weight distribution of keywords in the AI technology field.',
      json: {
        type: 'word-cloud',
        data: [
          { text: 'Machine Learning', value: 100 },
          { text: 'Deep Learning', value: 95 },
          { text: 'NLP', value: 88 },
          { text: 'Computer Vision', value: 85 },
          { text: 'LLM', value: 92 },
          { text: 'Reinforcement Learning', value: 72 },
          { text: 'Knowledge Graph', value: 65 },
          { text: 'Data Mining', value: 70 },
          { text: 'Neural Network', value: 80 },
          { text: 'Transfer Learning', value: 60 },
          { text: 'Generative AI', value: 90 },
          { text: 'GAN', value: 55 },
          { text: 'Attention Mechanism', value: 75 },
          { text: 'Pre-training', value: 82 },
          { text: 'Fine-tuning', value: 68 },
          { text: 'Multimodal', value: 86 },
          { text: 'Vector Database', value: 58 },
          { text: 'Prompt Engineering', value: 78 },
          { text: 'AI Agent', value: 84 },
          { text: 'GNN', value: 50 },
          { text: 'Bayesian', value: 45 },
          { text: 'Federated Learning', value: 48 },
          { text: 'Autonomous Driving', value: 76 },
          { text: 'Speech Recognition', value: 62 },
          { text: 'Recommendation System', value: 66 },
          { text: 'Anomaly Detection', value: 42 },
          { text: 'Time Series', value: 52 },
          { text: 'Text Classification', value: 40 },
          { text: 'Object Detection', value: 58 },
          { text: 'Semantic Segmentation', value: 46 },
        ],
        title: 'AI Technology Keywords',
      },
      dsl: 'vis word-cloud\ndata\n  - text "Machine Learning"\n    value 100\n  - text "Deep Learning"\n    value 95\n  - text "NLP"\n    value 88\n  - text "Computer Vision"\n    value 85\n  - text "LLM"\n    value 92\n  - text "Reinforcement Learning"\n    value 72\n  - text "Knowledge Graph"\n    value 65\n  - text "Data Mining"\n    value 70\n  - text "Neural Network"\n    value 80\n  - text "Transfer Learning"\n    value 60\n  - text "Generative AI"\n    value 90\n  - text "GAN"\n    value 55\n  - text "Attention Mechanism"\n    value 75\n  - text "Pre-training"\n    value 82\n  - text "Fine-tuning"\n    value 68\n  - text "Multimodal"\n    value 86\n  - text "Vector Database"\n    value 58\n  - text "Prompt Engineering"\n    value 78\n  - text "AI Agent"\n    value 84\n  - text "GNN"\n    value 50\n  - text "Bayesian"\n    value 45\n  - text "Federated Learning"\n    value 48\n  - text "Autonomous Driving"\n    value 76\n  - text "Speech Recognition"\n    value 62\n  - text "Recommendation System"\n    value 66\n  - text "Anomaly Detection"\n    value 42\n  - text "Time Series"\n    value 52\n  - text "Text Classification"\n    value 40\n  - text "Object Detection"\n    value 58\n  - text "Semantic Segmentation"\n    value 46\ntitle "AI Technology Keywords"',
    },
    {
      title: 'Display keyword weights for front-end development tech stack',
      description: 'Display keyword weights for front-end development tech stack',
      json: {
        type: 'word-cloud',
        data: [
          { text: 'React', value: 100 },
          { text: 'Vue', value: 92 },
          { text: 'TypeScript', value: 88 },
          { text: 'Next.js', value: 80 },
          { text: 'Webpack', value: 65 },
          { text: 'Vite', value: 78 },
          { text: 'CSS', value: 85 },
          { text: 'Tailwind', value: 75 },
          { text: 'Node.js', value: 82 },
          { text: 'GraphQL', value: 55 },
          { text: 'REST', value: 60 },
          { text: 'Svelte', value: 50 },
          { text: 'Angular', value: 58 },
          { text: 'Redux', value: 52 },
          { text: 'Zustand', value: 45 },
          { text: 'ESLint', value: 62 },
          { text: 'Prettier', value: 48 },
          { text: 'Jest', value: 56 },
          { text: 'Cypress', value: 42 },
          { text: 'Storybook', value: 40 },
          { text: 'Docker', value: 68 },
          { text: 'SSR', value: 70 },
          { text: 'SSG', value: 55 },
          { text: 'PWA', value: 38 },
          { text: 'WebAssembly', value: 35 },
          { text: 'Three.js', value: 44 },
          { text: 'D3.js', value: 46 },
          { text: 'Framer Motion', value: 40 },
          { text: 'React Query', value: 52 },
          { text: 'SWR', value: 36 },
        ],
        title: 'Front-End Development Tech Stack',
      },
      dsl: 'vis word-cloud\ndata\n  - text React\n    value 100\n  - text Vue\n    value 92\n  - text TypeScript\n    value 88\n  - text Next.js\n    value 80\n  - text Webpack\n    value 65\n  - text Vite\n    value 78\n  - text CSS\n    value 85\n  - text Tailwind\n    value 75\n  - text Node.js\n    value 82\n  - text GraphQL\n    value 55\n  - text REST\n    value 60\n  - text Svelte\n    value 50\n  - text Angular\n    value 58\n  - text Redux\n    value 52\n  - text Zustand\n    value 45\n  - text ESLint\n    value 62\n  - text Prettier\n    value 48\n  - text Jest\n    value 56\n  - text Cypress\n    value 42\n  - text Storybook\n    value 40\n  - text Docker\n    value 68\n  - text SSR\n    value 70\n  - text SSG\n    value 55\n  - text PWA\n    value 38\n  - text WebAssembly\n    value 35\n  - text Three.js\n    value 44\n  - text D3.js\n    value 46\n  - text "Framer Motion"\n    value 40\n  - text "React Query"\n    value 52\n  - text SWR\n    value 36\ntitle "Front-End Development Tech Stack"',
    },
    {
      title: 'Display keyword weights for data science terminology in academy theme',
      description: 'Display keyword weights for data science terminology',
      json: {
        type: 'word-cloud',
        data: [
          { text: 'Statistical Analysis', value: 95 },
          { text: 'Regression Analysis', value: 88 },
          { text: 'Hypothesis Testing', value: 72 },
          { text: 'ANOVA', value: 55 },
          { text: 'PCA', value: 65 },
          { text: 'Cluster Analysis', value: 78 },
          { text: 'Feature Engineering', value: 85 },
          { text: 'Cross-Validation', value: 60 },
          { text: 'Regularization', value: 52 },
          { text: 'Gradient Descent', value: 75 },
          { text: 'Loss Function', value: 68 },
          { text: 'Overfitting', value: 62 },
          { text: 'Data Cleaning', value: 80 },
          { text: 'Visualization', value: 90 },
          { text: 'A/B Testing', value: 70 },
          { text: 'Confidence Interval', value: 48 },
          { text: 'Decision Tree', value: 58 },
          { text: 'Random Forest', value: 72 },
          { text: 'SVM', value: 50 },
          { text: 'Dimensionality Reduction', value: 45 },
          { text: 'Sampling', value: 42 },
          { text: 'Normalization', value: 55 },
          { text: 'Encoding', value: 40 },
          { text: 'Pipeline', value: 46 },
          { text: 'Hyperparameter', value: 52 },
          { text: 'Ensemble Learning', value: 65 },
          { text: 'Cross-Entropy', value: 38 },
          { text: 'Evaluation Metrics', value: 58 },
          { text: 'Confusion Matrix', value: 44 },
          { text: 'ROC Curve', value: 48 },
        ],
        title: 'Data Science Terminology',
        theme: 'academy',
      },
      dsl: 'vis word-cloud\ndata\n  - text "Statistical Analysis"\n    value 95\n  - text "Regression Analysis"\n    value 88\n  - text "Hypothesis Testing"\n    value 72\n  - text "ANOVA"\n    value 55\n  - text "PCA"\n    value 65\n  - text "Cluster Analysis"\n    value 78\n  - text "Feature Engineering"\n    value 85\n  - text "Cross-Validation"\n    value 60\n  - text Regularization\n    value 52\n  - text "Gradient Descent"\n    value 75\n  - text "Loss Function"\n    value 68\n  - text Overfitting\n    value 62\n  - text "Data Cleaning"\n    value 80\n  - text Visualization\n    value 90\n  - text "A/B Testing"\n    value 70\n  - text "Confidence Interval"\n    value 48\n  - text "Decision Tree"\n    value 58\n  - text "Random Forest"\n    value 72\n  - text SVM\n    value 50\n  - text "Dimensionality Reduction"\n    value 45\n  - text Sampling\n    value 42\n  - text Normalization\n    value 55\n  - text Encoding\n    value 40\n  - text Pipeline\n    value 46\n  - text "Hyperparameter"\n    value 52\n  - text "Ensemble Learning"\n    value 65\n  - text "Cross-Entropy"\n    value 38\n  - text "Evaluation Metrics"\n    value 58\n  - text "Confusion Matrix"\n    value 44\n  - text "ROC Curve"\n    value 48\ntitle "Data Science Terminology"\ntheme academy',
    },
  ],
};
