import { Violin } from '@antv/gpt-vis';
import { Form, Input, Select } from 'antd';
import React, { useState } from 'react';

const data = [
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.9 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.7 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.1 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.6 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.6 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.7 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.9 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.6 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 2.9 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.1 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.1 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.9 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.7 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.1 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.1 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.1 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.3 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.2 },
  { group: 'I. setosa', category: 'SepalWidth', value: 4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 4.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.7 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.9 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.7 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.8 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.7 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.8 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.7 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.7 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.6 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.6 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.5 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.7 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.3 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.9 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.2 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.2 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.7 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.1 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.1 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 4.1 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.2 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 4.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.1 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.9 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.2 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.1 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.6 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.9 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.4 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 2.3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.3 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.4 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.6 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.5 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.4 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.9 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.8 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.3 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.8 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.6 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.8 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.1 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.2 },
  { group: 'I. setosa', category: 'SepalLength', value: 4.6 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.5 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.7 },
  { group: 'I. setosa', category: 'SepalLength', value: 5.3 },
  { group: 'I. setosa', category: 'PetalWidth', value: 0.2 },
  { group: 'I. setosa', category: 'PetalLength', value: 1.4 },
  { group: 'I. setosa', category: 'SepalWidth', value: 3.3 },
  { group: 'I. setosa', category: 'SepalLength', value: 5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.4 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.9 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.1 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.9 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.6 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.6 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.3 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.3 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.4 },
  { group: 'I. versicolor', category: 'SepalLength', value: 4.9 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.6 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.9 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.7 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.2 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.2 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.9 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.1 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.6 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.1 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.1 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.7 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.8 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.2 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.9 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.5 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.8 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.8 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.2 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.9 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.1 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.9 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.5 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.3 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.2 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.1 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.3 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.4 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.8 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.8 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.7 },
  { group: 'I. versicolor', category: 'PetalLength', value: 5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.6 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.8 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.4 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.4 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.2 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.9 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.7 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.8 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.6 },
  { group: 'I. versicolor', category: 'PetalLength', value: 5.1 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.7 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.4 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.6 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.5 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.4 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.5 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.7 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3.1 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.3 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.1 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.5 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.2 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.6 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.4 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.6 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.1 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.2 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.6 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.8 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3.3 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.2 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.7 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.6 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.2 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.2 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 3 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.2 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.7 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.3 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.9 },
  { group: 'I. versicolor', category: 'SepalLength', value: 6.2 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.1 },
  { group: 'I. versicolor', category: 'PetalLength', value: 3 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.5 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.1 },
  { group: 'I. versicolor', category: 'PetalWidth', value: 1.3 },
  { group: 'I. versicolor', category: 'PetalLength', value: 4.1 },
  { group: 'I. versicolor', category: 'SepalWidth', value: 2.8 },
  { group: 'I. versicolor', category: 'SepalLength', value: 5.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'PetalLength', value: 6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.9 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.7 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.8 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.1 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.9 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.2 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.8 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.5 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.6 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.7 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'SepalLength', value: 4.9 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.3 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.9 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.8 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.6 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.2 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.5 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.9 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.3 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.7 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.8 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.4 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.8 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.3 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.5 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.2 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.7 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.6 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.5 },
  { group: 'I. virginica', category: 'PetalLength', value: 5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 6 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.7 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.9 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.6 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.7 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.7 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.7 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.2 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.8 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.2 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.1 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.6 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.8 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.2 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.9 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.4 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.9 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.2 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.5 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.8 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.4 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.6 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.1 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 6.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 7.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.4 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.4 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.1 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.4 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 4.8 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.1 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.4 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.1 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.9 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.4 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.6 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.1 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.1 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.9 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.9 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.7 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.8 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.9 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.2 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.8 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.7 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.2 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.7 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.9 },
  { group: 'I. virginica', category: 'PetalLength', value: 5 },
  { group: 'I. virginica', category: 'SepalWidth', value: 2.5 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.3 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.2 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.5 },
  { group: 'I. virginica', category: 'PetalWidth', value: 2.3 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.4 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3.4 },
  { group: 'I. virginica', category: 'SepalLength', value: 6.2 },
  { group: 'I. virginica', category: 'PetalWidth', value: 1.8 },
  { group: 'I. virginica', category: 'PetalLength', value: 5.1 },
  { group: 'I. virginica', category: 'SepalWidth', value: 3 },
  { group: 'I. virginica', category: 'SepalLength', value: 5.9 },
];

const themes = ['default', 'academy', 'dark'] as const;
export const PALETTE_1 = ['#8459fc', '#ff89bd', '#1677ff', '#00c2ff', '#ff9a00'];
export const PALETTE_2 = ['#1B9E77', '#D95F02', '#7570B3', '#E7298A', '#66A61E'];
export const PALETTE_3 = ['#7593ed', '#95e3b0', '#6c7893', '#e7c450', '#7460eb'];

export default () => {
  const [theme, setTheme] = useState<'default' | 'academy' | 'dark'>('default');
  const [backgroundColor, setBackgroundColor] = useState<string>('');
  const [palette, setPalette] = useState<string[]>([]);

  const onValuesChange = (changedValues: {
    theme: 'default' | 'academy' | 'dark';
    lineWidth: number;
    backgroundColor: string;
    palette: string[];
  }) => {
    if (changedValues.theme) {
      setTheme(changedValues.theme);
      setPalette([]);
    }
    if (changedValues.backgroundColor !== undefined)
      setBackgroundColor(changedValues.backgroundColor);
    if (changedValues.palette !== undefined) {
      let newPalette = changedValues.palette;
      if (typeof newPalette === 'string') {
        try {
          newPalette = JSON.parse(newPalette);
        } catch {
          newPalette = [];
        }
      }
      setPalette(Array.isArray(newPalette) ? newPalette : []);
    } else {
      setPalette([]);
    }
  };

  return (
    <div>
      <Form
        layout="inline"
        style={{ marginBottom: 12 }}
        initialValues={{ theme, backgroundColor, palette }}
        key={theme}
        onValuesChange={onValuesChange}
      >
        <Form.Item label="Theme" name="theme" style={{ marginBottom: 6 }}>
          <Select style={{ width: 120 }} options={themes.map((t) => ({ label: t, value: t }))} />
        </Form.Item>
        <Form.Item
          label="Background"
          name="backgroundColor"
          rules={[
            {
              pattern: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
              message: '请输入有效的色值编码，例如 #fff 或 #ffffff',
            },
          ]}
          style={{ marginBottom: 6 }}
        >
          <Input placeholder="#ffffff" style={{ width: 120 }} />
        </Form.Item>
        <Form.Item label="Palette" name="palette" style={{ marginBottom: 6 }}>
          <Select
            placeholder="选择调色板"
            style={{ width: 200 }}
            options={[
              {
                label: `色板1: ${PALETTE_1.join(', ')}`,
                value: JSON.stringify(PALETTE_1),
              },
              {
                label: `色板2: ${PALETTE_2.join(', ')}`,
                value: JSON.stringify(PALETTE_2),
              },
              {
                label: `色板3: ${PALETTE_3.join(', ')}`,
                value: JSON.stringify(PALETTE_3),
              },
            ]}
            allowClear
          />
        </Form.Item>
      </Form>
      <Violin
        data={data}
        title="Box Plot Example"
        theme={theme}
        style={{ backgroundColor, palette }}
      />
    </div>
  );
};
