name: Deploy Site

on:
  workflow_dispatch:
  release:
    # released: only latest release will trigger
    types: [released]

concurrency:
  group: '${{ github.workflow }} - ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  publish-site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm docs:build
      - run: |
          echo "gpt-vis.antv.vision" > docs-dist/CNAME
      - run: |
          cd docs-dist
          git init
          git config --local user.name antv
          git config --local user.email antv@antfin.com
          git add .
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          directory: docs-dist
          branch: gh-pages
          force: true
