import {
  Activity,
  AreaChart,
  BarChart2,
  BarChart3,
  BarChartHorizontal,
  CircleDot,
  Cloud,
  Droplets,
  FileText,
  Filter,
  Fish,
  GitBranch,
  LayoutGrid,
  LineChart,
  List,
  Network,
  PieChart,
  Radar,
  ScatterChart,
  Share2,
  Table,
  TrendingDown,
  TrendingUp,
  Users,
  Workflow,
  type LucideIcon,
} from 'lucide-react';

export const chartIcons: Record<string, LucideIcon> = {
  'area-chart': AreaChart,
  'bar-chart': BarChartHorizontal,
  boxplot: BarChart3,
  'column-chart': BarChart2,
  'dual-axes': TrendingUp,
  'fishbone-diagram': Fish,
  'flow-diagram': GitBranch,
  'funnel-chart': Filter,
  histogram: BarChart3,
  'indented-tree': List,
  'line-chart': LineChart,
  'liquid-chart': Droplets,
  mindmap: Network,
  'network-graph': Share2,
  'organization-chart': Users,
  'pie-chart': PieChart,
  'radar-chart': Radar,
  'sankey-diagram': Workflow,
  'scatter-chart': ScatterChart,
  table: Table,
  treemap: LayoutGrid,
  'venn-diagram': CircleDot,
  'violin-chart': Activity,
  'waterfall-chart': TrendingDown,
  wordcloud: Cloud,
  summary: FileText,
};
